{
 "title": "Prusa",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Bed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Bed",
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "select mean(value) from \"t_bed\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "t_bed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "t_bed",
     "tags": [
      { "key": "host", "operator": "=", "value": "Prusa" }
     ]
    },
    {
     "alias": "Target",
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "select mean(value) from \"t_bed_target\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "t_bed_target" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "t_bed_target",
     "tags": [
      { "key": "host", "operator": "=", "value": "Prusa" }
     ]
    }
   ]
  },
  {
   "title": "Extruder",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Extruder",
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "select mean(value) from \"t_ex\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "t_ex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "t_ex",
     "tags": [
      { "key": "host", "operator": "=", "value": "Prusa" }
     ]
    },
    {
     "alias": "Target",
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "select mean(value) from \"t_ex_target\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "t_ex_target" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "t_ex_target",
     "tags": [
      { "key": "host", "operator": "=", "value": "Prusa" }
     ]
    }
   ]
  },
  {
   "title": "Completion",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "function": "last",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "select last(value) from \"completion\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "completion" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "completion",
     "tags": [
      { "key": "host", "operator": "=", "value": "Prusa" }
     ]
    }
   ]
  },
  {
   "title": "Print Time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "function": "last",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "select last(value) from \"printTime\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "printTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "printTime",
     "tags": [
      { "key": "host", "operator": "=", "value": "Prusa" }
     ]
    }
   ]
  },
  {
   "title": "Print Time Left",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "function": "last",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "select last(value) from \"printTimeLeft\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "printTimeLeft" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "printTimeLeft",
     "tags": [
      { "key": "host", "operator": "=", "value": "Prusa" }
     ]
    }
   ]
  }
 ]
}